import { Metadata } from "next"
import "./global.css"
import Navbar from "@/components/navbar"
import  ReduxProvider  from "../../redux/reduxProvider"


export const metadata : Metadata = {
  title: {
    default:'Next.js tutorial Learning',
    template:"%s | Next Learning"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  

  return (

    <ReduxProvider>
      <html lang="en">
        <body>
          {/* <Navbar/> */}
          <div className="container mx-auto">    
            {children}
          </div>
          {/* <footer style={{backgroundColor:"lightgrey",padding:"0.2rem"}} className="mt-4">
            <h3>footer</h3>
          </footer> */}
        </body>
      </html>
    </ReduxProvider>
  )
}
