export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
      <body>
        <header style={{backgroundColor:"lightblue",padding:"0.2rem"}}>
          <h2>Header</h2>
        </header>
        
        {children}

        <footer style={{backgroundColor:"lightgrey",padding:"0.2rem"}}>
          <h3>footer</h3>
        </footer>
      </body>
    </html>
    </>
  )
}
